### ISSUE TITLE
unknown tokenizer: perl

### ISSUE THREAD

**Issue by eserte** [sekia/Search-Fulltext-Tokenizer-Ngram#1]
On my smoker machines I see the following test failure:
```
DBD::SQLite::db do failed: unknown tokenizer: perl at /home/cpansand/.cpan/build/2016112506/Search-Fulltext-1.03-wb0jil/blib/lib/Search/Fulltext/SQLite.pm line 49.
    # Looks like you planned 0 tests but ran 1.
DBD::SQLite::db do failed: unknown tokenizer: perl at /home/cpansand/.cpan/build/2016112506/Search-Fulltext-1.03-wb0jil/blib/lib/Search/Fulltext/SQLite.pm line 49.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 2.
t/Search/Fulltext/Tokenizer/Ngram.t .. 
Dubious, test returned 255 (wstat 65280, 0xff00)
All 2 subtests passed 
```
Probably this is caused by this change in DBD::SQLite: https://metacpan.org/source/ISHIGAKI/DBD-SQLite-1.52/Changes#L32

**Comment by sekia** [comment]
Indeed the issue seems to be caused by DBD::SQlite 1.52, which disabled Perl tokenizer feature for security.
Since version 1.54 of the module re-enabled the feature, I could pass the test again so I think no modification for the issue is necessary now.
Thank you for specific report and I'm sorry for late response!
